### PR TITLE
Refactor some of people page code

### PR DESCRIPTION
**Pull request by ColinMcNeil**
Fix people id loading to be dynamic

### CODE REVIEW

**Comment by gluxon** [comment]
`document.querySelector` is something can can usually be avoided in DOM libraries like Vue. Is there a particular reason we're doing it this way rather than updating html attributes like `class` declaratively through the template?

**Comment by ColinMcNeil** [comment]
We could also use refs I think

**Comment by gluxon** [comment]
Refs would be better than document.querySelector, but using DOM references is still doing things imperatively. That kind if defeats the purpose of a declarative view library like Vue.

To do things declaratively, bind the class attribute and apply the "immediate" and "penultimate" classes based on a getter or data expression.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ColinMcNeil** [comment]
@gluxon What do you think? I'm proud of this one.

**Comment by gluxon** [comment]
I haven't tested it, but wow, you should be.

**Pull request merged**
