### PR TITLE
Mobile navigation

### PR DESCRIPTION
**Pull request by alecmakeus**

### CODE REVIEW

**Comment by gluxon** [comment]
Looks awesome! Commits are well structured. Great job!

**Comment by gluxon** [comment]
I do see a "This branch is out of sync with the base branch" error thoug that's preventing merge. Can you try rebasing to see if that fixes things?

Probably just needs: git rebase origin/develop.

**Comment by alecmakeus** [comment]
```$ git rebase origin/develop
Current branch mobile-navigation is up to date.```

**Comment by ColinMcNeil** [comment]
Looks like it's good to merge. It failed CI, but I restarted the build.

**Comment by gluxon** [comment]
@ColinMcNeil I would have preferred that merge commit removed before pulling this into develop. Merge commits break the linear history of the project and make it harder to use tools like git bisect later. They also make changes harder to see because they typically resolve conflicts in a way that doesn't separate it from other changes. We've had bugs reintroduced twice into projects because merge commits being hard to review.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ColinMcNeil** [comment]
I didn't make a merge commit

**Comment by gluxon** [comment]
What's kind of interesting now that I noticed is that you actually got rid of it (which is what we wanted to do) by rebase merging it in. 😅✌️

So I guess we know in the future that clean merge commits don't survive after a rebase merge.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
